In [1]:
import pandas as pd
import numpy as np

In [2]:
## Correlation and Covariance
temperature=[98,87,90,85,95,75]
numberofcustomers=[15,12,10,10,16,7]
gender=['M','F','T','M','M','F']
Rating=['Good','Excellent','Bad','Good','Excellent','Good']

## Creating the dataframe from the above two lists
icecream = pd.DataFrame(list(zip(temperature, numberofcustomers,gender,Rating)), columns =['temperature', 'numberofcustomers','Gender','Rating'])
icecream

temperature  numberofcustomers Gender     Rating
0           98                 15      M       Good
1           87                 12      F  Excellent
2           90                 10      T        Bad
3           85                 10      M       Good
4           95                 16      M  Excellent
5           75                  7      F       Good

In [4]:
from sklearn.preprocessing import LabelEncoder
LE_Rating=LabelEncoder()

LE_Rating.fit(icecream['Rating'])

LE_Rating_Transform=LE_Rating.transform(icecream['Rating'])

icecream['Rating_Transformed']=LE_Rating_Transform
icecream

#LE_Rating_Transform

temperature  numberofcustomers Gender     Rating  Rating_Transformed
0           98                 15      M       Good                   2
1           87                 12      F  Excellent                   1
2           90                 10      T        Bad                   0
3           85                 10      M       Good                   2
4           95                 16      M  Excellent                   1
5           75                  7      F       Good                   2

In [5]:
LE_Rating.classes_

array(['Bad', 'Excellent', 'Good'], dtype=object)

In [13]:
LE_Rating.fit_transform(icecream['Rating'])

array([2, 1, 0, 2, 1, 2])

In [19]:
LE_Rating.set_params()

LabelEncoder()

In [9]:
LE_Rating.transform(test['Rating'])

array([2, 1, 2])

In [ ]:
### Using Dictionary

In [7]:
dict_rating={"Good":1,"Excellent":3,"Bad":0}

In [8]:
icecream=icecream.replace({"Rating": dict_rating})

In [9]:
icecream

temperature  numberofcustomers Gender  Rating  Rating_Transformed
0           98                 15      M       1                   2
1           87                 12      F       3                   1
2           90                 10      T       0                   0
3           85                 10      M       1                   2
4           95                 16      M       3                   1
5           75                  7      F       1                   2

In [10]:
temperature=[85,95,75]
numberofcustomers=[10,16,7]
gender=['M','M','F']
Rating=['Good','Excellent','Good','Average']

## Creating the dataframe from the above two lists
test = pd.DataFrame(list(zip(temperature, numberofcustomers,gender,Rating)), columns =['temperature', 'numberofcustomers','Gender','Rating'])
test

temperature  numberofcustomers Gender     Rating
0           85                 10      M       Good
1           95                 16      M  Excellent
2           75                  7      F       Good

In [11]:
LE_Rating.transform(test['Rating'])

array([2, 1, 2])