In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [3]:
len?

In [4]:
def square(a):
    """It will the square a given number"""
    return a*a

In [5]:
def donothing(x):
    return(x)

In [6]:
%%timeit
donothing(10)

123 ns ± 0.887 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [7]:
print(_)

In [8]:
_12

NameError: name '_12' is not defined

In [ ]:
L = list(range(10))
L

In [ ]:
for c in L:
    L2=str(c)

In [ ]:
L2 =[str(c) for c in L]
L2

In [ ]:
L3 = [True, "2", 3.0, 4] 
[type(d) for d in L3]

In [ ]:
a=range(10)
print(a)

for i in a:
    print(i)

a=list(a)
type(a)
print(a)

for i in range(len(a)):
    print(a[i])
    
type(a[1])

In [ ]:
 [str(c) for c in a]

In [ ]:
for i in a:
    print(str(i))

In [ ]:
import array
L=list(range(10))
A=array.array('i',L)
A

In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

In [ ]:
np.array([print(range(i, i + 3)) for i in [2, 4, 7]])

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

In [ ]:
range(2,2+3)

In [ ]:
print(a)

###### https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html

In [10]:
import numpy as np
np.random.seed(0)  ## Seed for Reproducibility
x1=np.random.randint(10, size=6) ## One Dimensional Array
print(x1)
print('x1 dimensions :',x1.ndim,' x1 shape :',x1.shape,' x1 size : ',x1.size)
x2=np.random.randint(10,size=(3,4)) # Two-dimensional array
print(x2)
print('x2 dimensions :',x2.ndim,' x2 shape :',x2.shape,' x2 size : ',x2.size)
x3=np.random.randint(10,size=(3,4,5)) # Three-dimensional array
print(x3)
print('x3 dimensions :',x3.ndim,' x3 shape :',x3.shape,' x3 size : ',x3.size)

print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

[5 0 3 3 7 9]
x1 dimensions : 1  x1 shape : (6,)  x1 size :  6
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x2 dimensions : 2  x2 shape : (3, 4)  x2 size :  12
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 dimensions : 3  x3 shape : (3, 4, 5)  x3 size :  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


In [11]:
import pandas as pd
x1_df=pd.DataFrame(x1)
print(x1_df.shape)
x2_df=pd.DataFrame(x2)
print(x2_df.shape)
x2_df.head()
#x3_df=pd.DataFrame(x3) # This is not valid Case
#print(x3_df.shape)

(6, 1)
(3, 4)


0  1  2  3
0  3  5  2  4
1  7  6  8  8
2  1  6  7  7

In [ ]:
## Accessing single elements in array

In [12]:
print(x1)
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])

[5 0 3 3 7 9]
5
7
9
7


In [13]:
print(x2)
print(x2[0])
print(x2[0,0])
print(x2[2,0])
print(x2[2,-1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[3 5 2 4]
3
1
7


In [ ]:
x2[0,0]=12

In [14]:
## Array Slicing
#x[start:stop:step]
x=np.arange(10)
print(x)
print(x[:5])  # first five elements
print(x[5:])  # elements after index 5
print(x[4:7])  # middle sub-array
print(x[::2])  # every other element
print(x[1::2])  # every other element starting at index 1
print(x[::-1]) # all elements, reversed
print(x[5::-1])
print(x[5:2:-2])
print(x[2:5:2])
print(x[5:2:1]) ## Empty list will be printed

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 4 3 2 1 0]
[5 3]
[2 4]
[]


In [ ]:
##Multi-dimensional subarrays
##Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:

In [23]:
print(x2)
print(x2[:2,:3])
print(x2[:2,::2])
print(x2[:2,1::2])
print(x2[::-1,::2])
print(x2[::-1,::-2])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]
[[3 2]
 [7 8]]
[[5 4]
 [6 8]]
[[1 7]
 [7 8]
 [3 2]]
[[7 6]
 [8 6]
 [4 5]]


In [24]:
### Accessing array rows and columns

In [26]:
print(x2[:, 0])  # first column of x2
print(x2[0,:])

[3 7 1]
[3 5 2 4]


In [31]:
print(x2)
x2_copy=x2[:2,:2].copy()
print(x2_copy)
x2_copy[0,0]=99
print(x2_copy)
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5]
 [7 6]]
[[99  5]
 [ 7  6]]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [ ]:
### Reshaping the array

In [33]:
grid=np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
x=np.array([1,2,3])
xx=np.random.randint(4,size=3)
xx
x
xxx=x.reshape(1,3)
xxx.ndim
xx.ndim

xxx_df=pd.DataFrame(xxx)
print(xxx_df)

xxxx=x.reshape(3,1)
xxxx_df=pd.DataFrame(xxxx)
print(xxxx_df)



   0  1  2
0  1  2  3
   0
0  1
1  2
2  3


In [57]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate([x,y])
print(z)
z=[99,99,99]
print(np.concatenate([x,y,z]))

[1 2 3 4 5 6]
[ 1  2  3  4  5  6 99 99 99]


In [62]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(np.concatenate([grid,grid],axis=0))
print('*****')
print(np.concatenate([grid,grid],axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
*****
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [72]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [78]:
grid=np.arange(16).reshape(4,4)
print(grid)
print(np.vsplit(grid,[2]))
print(np.hsplit(grid,[3]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [90]:
np.random.seed(0)
def compute_reciprocals(values):
    output=np.empty(len(values)) 
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output
        
values=np.random.randint(1,10, size=5)
reciprocal_output=compute_reciprocals(values)
print(reciprocal_output)

[0.16666667 1.         0.25       0.25       0.125     ]


In [91]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

5.19 s ± 497 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [92]:
print(1/values)

[0.16666667 1.         0.25       0.25       0.125     ]


In [93]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [95]:
## Array Arthematic
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [96]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [97]:
print(np.add(x, 2))
The following table lists the arithmetic operators implemented in NumPy:

Operator	Equivalent ufunc	Description
+	np.add	Addition (e.g., 1 + 1 = 2)
-	np.subtract	Subtraction (e.g., 3 - 2 = 1)
-	np.negative	Unary negation (e.g., -2)
*	np.multiply	Multiplication (e.g., 2 * 3 = 6)
/	np.divide	Division (e.g., 3 / 2 = 1.5)
//	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**	np.power	Exponentiation (e.g., 2 ** 3 = 8)
%	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)

[2 3 4 5]


In [98]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [108]:
x=[1,2,3]
x1=np.arange(10)
y=[1,2,3,4]
print(x1+5)
np.add(x1,x1)
np.add(x,2)

[ 5  6  7  8  9 10 11 12 13 14]


array([3, 4, 5])

In [109]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [114]:
theta=np.linspace(0,4,3)
theta
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

theta      =  [0. 2. 4.]
sin(theta) =  [ 0.          0.90929743 -0.7568025 ]
cos(theta) =  [ 1.         -0.41614684 -0.65364362]
tan(theta) =  [ 0.         -2.18503986  1.15782128]


In [116]:
## Specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [119]:
x=[1,2,3]
type(x)
np.add.reduce(x)
np.add.accumulate(x)

array([1, 3, 6], dtype=int32)

In [121]:
x = np.arange(1, 6)
print(x)
np.multiply.outer(x, x)

[1 2 3 4 5]


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [125]:
L=np.random.random(100)
sum(L)

50.684472748210915

In [127]:
print(np.random.random(20))
print(np.random.randint(20,size=20))

[0.41224358 0.54175922 0.22209216 0.45803492 0.23090228 0.74940011
 0.65656829 0.51324137 0.67519693 0.43960314 0.1163365  0.44355178
 0.24505542 0.64322067 0.25284067 0.95285657 0.43699403 0.00529613
 0.1335414  0.49690312]
[ 6 11  7 19 14 19  7  8 19  3  9  2 18  7 10  8  1 10  2  1]


In [132]:
M=np.random.random((3,4))
print(M)
print(np.sum(M,axis=0))
print(np.sum(M,axis=1))

[[0.82328792 0.09875229 0.87117706 0.66234081]
 [0.01071371 0.51693147 0.49144541 0.51507624]
 [0.37062493 0.21979151 0.08013632 0.51179663]]
[1.20462656 0.83547527 1.44275879 1.68921368]
[2.45555808 1.53416683 1.18234939]


In [139]:
list=[1,2]
np.all(list)

True

In [ ]:
Function Name	NaN-safe Version	Description
np.sum	np.nansum	Compute sum of elements
np.prod	np.nanprod	Compute product of elements
np.mean	np.nanmean	Compute mean of elements
np.std	np.nanstd	Compute standard deviation
np.var	np.nanvar	Compute variance
np.min	np.nanmin	Find minimum value
np.max	np.nanmax	Find maximum value
np.argmin	np.nanargmin	Find index of minimum value
np.argmax	np.nanargmax	Find index of maximum value
np.median	np.nanmedian	Compute median of elements
np.percentile	np.nanpercentile	Compute rank-based statistics of elements
np.any	N/A	Evaluate whether any elements are true
np.all	N/A	Evaluate whether all elements are true

In [ ]:
## Broadcasting

In [140]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [141]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [143]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [154]:
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [163]:
a=np.arange(3)
print(a)
b=np.random.randint(10,size=(3,3))
print(b)
a+b

[0 1 2]
[[0 4 6]
 [4 0 9]
 [3 3 7]]


array([[ 0,  5,  8],
       [ 4,  1, 11],
       [ 3,  4,  9]])

In [153]:
b.shape

(3, 1)

In [171]:
M=np.ones((2,3))
print(M)
A=np.arange(3)
print(A)

M+A

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


array([[1., 2., 3.],
       [1., 2., 3.]])

In [173]:
a = np.arange(3).reshape((3, 1))
print(a)
b = np.arange(3)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]


In [175]:
##Comparison Operators as ufuncs

In [176]:
x = np.array([1, 2, 3, 4, 5])

In [177]:
x<3

array([ True,  True, False, False, False])

In [178]:
x>3

array([False, False, False,  True,  True])

In [179]:
x<=3

array([ True,  True,  True, False, False])

In [180]:
x>=3

array([False, False,  True,  True,  True])

In [181]:
x!=3

array([ True,  True, False,  True,  True])

In [182]:
x==3

array([False, False,  True, False, False])

In [183]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [ ]:

Operator	Equivalent ufunc		Operator	Equivalent ufunc
==	np.equal		!=	np.not_equal
<	np.less		<=	np.less_equal
>	np.greater		>=	np.greater_equal

In [184]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [185]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [186]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [187]:
np.sum(x < 6)

8

In [188]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [189]:
np.any(x > 8)

True

In [190]:
np.any(x < 0)

False

In [191]:
# are all values less than 10?
np.all(x < 10)

True

In [192]:
# are all values equal to 6?
np.all(x == 6)

False

In [193]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

In [194]:
np.sum((inches > 0.5) & (inches < 1))

NameError: name 'inches' is not defined

In [ ]:
print("Number days without rain:      ", np.sum(inches == 0))
print("Number days with rain:         ", np.sum(inches != 0))
print("Days with more than 0.5 inches:", np.sum(inches > 0.5))
print("Rainy days with < 0.2 inches  :", np.sum((inches > 0) &
                                                (inches < 0.2)))