In [5]:
import numpy as np
import pandas as pd
import spacy
import nltk
import keras

Using TensorFlow backend.


In [19]:
# define documents
docs = ['Well done! Prudhvi',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Weak',
'Poor effort!',
'not good',
'poor work prudhvi',
'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [18]:
vocab_size = 50
encoded_docs = [keras.preprocessing.text.one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[10, 6, 43], [29, 43], [2, 47], [2, 19], [47], [14], [13, 47], [15, 29], [13, 19, 43], [46, 30, 6, 23]]


In [20]:
max_length = 4
padded_docs =  keras.preprocessing.sequence.pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[10  6 43  0]
 [29 43  0  0]
 [ 2 47  0  0]
 [ 2 19  0  0]
 [47  0  0  0]
 [14  0  0  0]
 [13 47  0  0]
 [15 29  0  0]
 [13 19 43  0]
 [46 30  6 23]]
