In [12]:
from sklearn.model_selection import learning_curve
from sklearn.svm import SVC
import numpy as np
from sklearn.model_selection import validation_curve
from sklearn.datasets import load_iris
from sklearn.linear_model import Ridge

np.random.seed(0)
iris = load_iris()
X, y = iris.data, iris.target
indices = np.arange(y.shape[0])
np.random.shuffle(indices)
X, y = X[indices], y[indices]

train_sizes, train_scores, valid_scores = learning_curve(SVC(kernel='linear'), X, y, train_sizes=[50, 60,70,80, 90,110], cv=5)

In [13]:
train_scores

array([[0.98      , 0.98      , 0.98      , 0.98      , 0.98      ],
       [0.98333333, 1.        , 0.98333333, 0.98333333, 0.98333333],
       [0.98571429, 1.        , 0.98571429, 0.98571429, 0.98571429],
       [0.9875    , 1.        , 0.9875    , 0.9875    , 0.9875    ],
       [0.98888889, 1.        , 0.98888889, 0.98888889, 0.98888889],
       [0.98181818, 1.        , 0.98181818, 0.98181818, 0.99090909]])

In [14]:
valid_scores

array([[1.        , 0.93333333, 1.        , 1.        , 0.96666667],
       [1.        , 0.96666667, 1.        , 1.        , 0.96666667],
       [1.        , 0.96666667, 1.        , 1.        , 0.96666667],
       [1.        , 0.96666667, 1.        , 1.        , 0.96666667],
       [1.        , 0.96666667, 1.        , 1.        , 1.        ],
       [1.        , 0.96666667, 1.        , 1.        , 0.96666667]])

In [19]:
import numpy as np
np.mean(train_scores,axis=1)

array([0.98      , 0.98666667, 0.98857143, 0.99      , 0.99111111,
       0.98727273])

In [ ]:
import matplotlib.pyplot as plt