In [24]:
import torch
import torch.nn as nn

In [12]:
w=torch.tensor(3.0,requires_grad=True)
b=torch.tensor(1.0,requires_grad=True)
x=7
y=w*x+b
print(y)

tensor(22., grad_fn=<AddBackward0>)


In [7]:
def forward(x):
    y=w*x+b
    return y

In [10]:
x=torch.tensor([[2],[7]])
forward(x)

tensor([[ 7],
        [22]], grad_fn=<AddBackward0>)

In [ ]:
## Linear Class

In [13]:
import torch
from torch.nn import Linear

In [35]:
torch.manual_seed(1)
model=Linear(in_features=1,out_features=1)
print(model.bias,model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [19]:
x=torch.tensor([[2.0],[3.0]])
model(x)

tensor([[0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)

In [33]:
class LR(nn.Module):
    def __init__(self,input_size,output_size):
        super().__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        pred=self.linear(x)
        return pred

In [36]:
torch.manual_seed(1)
model=LR(1,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [37]:
x=torch.tensor([1.0])
print(model.forward(x))

tensor([0.0739], grad_fn=<AddBackward0>)
