In [25]:
import os
#os.chdir('C:\\Users\\Administrator\\Desktop\\Prudhvi\\Prudhvi\\Data Science\\Data')
os.chdir('C:\\Users\\Administrator\\Desktop\\Prudhvi\\Prudhvi\\Data Science\\Data')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

Reading the file

In [26]:
pd.options.display.max_columns = None
#Home
#telco=pd.read_csv('Telco_Customer_Attr.csv')
#Office
telco=pd.read_csv('Teleco_Cust_Attr.csv')
telco.head()
#print(telco.shape)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

Checking the columns if any othem contains null or not

In [27]:
telco.isnull().any()

customerID          False
gender              False
SeniorCitizen       False
Partner             False
Dependents          False
tenure              False
PhoneService        False
MultipleLines       False
InternetService     False
OnlineSecurity      False
OnlineBackup        False
DeviceProtection    False
TechSupport         False
StreamingTV         False
StreamingMovies     False
Contract            False
PaperlessBilling    False
PaymentMethod       False
MonthlyCharges      False
TotalCharges         True
Churn               False
dtype: bool

Fixing the missing values using the Stratified mean value imputation

In [28]:
Mean_No_TotalCharges=telco.groupby('Churn')['TotalCharges'].mean()['No']
Mean_Yes_TotalCharges=telco.groupby('Churn')['TotalCharges'].mean()['Yes']

In [29]:
telco.loc[(telco['TotalCharges'].isnull()) & (telco['Churn']=='No'),['TotalCharges']]=Mean_No_TotalCharges
telco.loc[(telco['TotalCharges'].isnull()) & (telco['Churn']=='Yes'),['TotalCharges']]=Mean_Yes_TotalCharges

Dropping the columns which dont explain much variance

In [30]:
telco.drop(['customerID'],axis=1,inplace=True)

In [31]:
telco.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [32]:
telco.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

Data type conversion

In [33]:
telco['SeniorCitizen']=telco['SeniorCitizen'].astype('object')

In [34]:
telco_backup=telco

In [35]:
from sklearn.preprocessing import LabelBinarizer
from collections import defaultdict
import pandas as pd
encoding=defaultdict(LabelBinarizer)
columns_nominal=['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','PaymentMethod']
for i in columns_nominal:
    encoded_df=pd.DataFrame()
    d=pd.DataFrame(encoding[i].fit_transform(telco[i]))
    test_column=d.columns.values
    list1=[i+'_'+str(j) for j in test_column]
    d.columns=list1
    encoded_df=pd.concat([encoded_df,d],axis=1)
    telco.drop(i,axis=1, inplace=True)
    telco=pd.concat([telco,encoded_df],axis=1)

In [36]:
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
telco['Contract']=lb_make.fit_transform(telco["Contract"])

In [37]:
telco.head()

SeniorCitizen  tenure  Contract  MonthlyCharges  TotalCharges Churn  \
0             0       1         0           29.85         29.85    No   
1             0      34         1           56.95       1889.50    No   
2             0       2         0           53.85        108.15   Yes   
3             0      45         1           42.30       1840.75    No   
4             0       2         0           70.70        151.65   Yes   

   gender_0  Partner_0  Dependents_0  PhoneService_0  MultipleLines_0  \
0         0          1             0               0                0   
1         1          0             0               1                1   
2         1          0             0               1                1   
3         1          0             0               0                0   
4         0          0             0               1                1   

   MultipleLines_1  MultipleLines_2  InternetService_0  InternetService_1  \
0                1                0                  1                  0   
1                0                0                  1                  0   
2                0                0                  1                  0   
3                1                0                  1                  0   
4                0                0                  0                  1   

   InternetService_2  OnlineSecurity_0  OnlineSecurity_1  OnlineSecurity_2  \
0                  0                 1                 0                 0   
1                  0                 0                 0                 1   
2                  0                 0                 0                 1   
3                  0                 0                 0                 1   
4                  0                 1                 0                 0   

   OnlineBackup_0  OnlineBackup_1  OnlineBackup_2  DeviceProtection_0  \
0               0               0               1                   1   
1               1               0               0                   0   
2               0               0               1                   1   
3               1               0               0                   0   
4               1               0               0                   1   

   DeviceProtection_1  DeviceProtection_2  TechSupport_0  TechSupport_1  \
0                   0                   0              1              0   
1                   0                   1              1              0   
2                   0                   0              1              0   
3                   0                   1              0              0   
4                   0                   0              1              0   

   TechSupport_2  StreamingTV_0  StreamingTV_1  StreamingTV_2  \
0              0              1              0              0   
1              0              1              0              0   
2              0              1              0              0   
3              1              1              0              0   
4              0              1              0              0   

   StreamingMovies_0  StreamingMovies_1  StreamingMovies_2  \
0                  1                  0                  0   
1                  1                  0                  0   
2                  1                  0                  0   
3                  1                  0                  0   
4                  1                  0                  0   

   PaperlessBilling_0  PaymentMethod_0  PaymentMethod_1  PaymentMethod_2  \
0                   1                0                0                1   
1                   0                0                0                0   
2                   1                0                0                0   
3                   0                1                0                0   
4                   1                0                0                1   

   PaymentMethod_3  
0                0  
1                1  
2                1

from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
#enc.fit(telco['gender_lb'])
enc.fit(telco['MultipleLines_LE'].values.reshape(-1,1))
X=enc.transform(telco['MultipleLines_LE'].values.reshape(-1,1)).toarray()


In [38]:
y=telco['Churn']
telco=telco.drop('Churn',axis=1)

#### Train test split

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(telco,y,test_size=0.30,random_state=42)

#### Applying  SVC Using GridSearchCV

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
scores=['precision', 'recall','f1']
for score in scores:
    parameters={'C':[10,100,1000,10000],'gamma':[0.1,0.01,0.001,0.0001,0.00001]}
    SVCGridSearch=GridSearchCV(SVC(kernel='rbf'),parameters,cv=3,scoring='%s_macro' % score)
    SVCGridSearch.fit(X_train,y_train)
    print('Best Parameters:',SVCGridSearch.best_params_)
    print('CV Results Keys: \n',SVCGridSearch.cv_results_.keys())
    print('CV Results: \n',SVCGridSearch.cv_results_)

Best Parameters: {'C': 100, 'gamma': 1e-05}
CV Results Keys: 
 dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_C', 'param_gamma', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score', 'split0_train_score', 'split1_train_score', 'split2_train_score', 'mean_train_score', 'std_train_score'])
CV Results: 
 {'mean_fit_time': array([ 1.39267095,  1.51945138,  0.96522148,  1.02404435,  1.05973768,
        1.41971207,  1.74856702,  1.35909891,  1.37246243,  1.7709024 ,
        1.60646852,  1.78752112,  2.30232469,  3.8578221 ,  3.97923136,
        2.30870954,  2.56753167,  3.42630744, 21.84541059, 17.54663499]), 'std_fit_time': array([0.03579301, 0.08370228, 0.00458179, 0.10094056, 0.01631384,
       0.0377641 , 0.1998703 , 0.00900357, 0.03851167, 0.0253026 ,
       0.21446829, 0.31372905, 0.09529241, 0.0733755 , 0.0676003 ,
       0.40462159, 0.45284133, 0.14754095, 1.84299042, 1

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
parameters={'C':[10,100,1000],'gamma':[0.1,0.01,0.001,0.0001,0.00001]}
SVCGridSearch=GridSearchCV(SVC(kernel='rbf'),parameters,cv=3)
SVCGridSearch.fit(X_train,y_train)
print('Best Parameters:',SVCGridSearch.best_params_)
print('CV Results Keys: \n',SVCGridSearch.cv_results_.keys())
print('CV Results: \n',SVCGridSearch.cv_results_)

In [77]:
from sklearn.svm import SVC
clf=SVC(C=100,gamma=0.001,kernel='rbf')
clf.fit(X_train,y_train)
SVCPredict_train=clf.predict(X_train)
SVCPredict_test=clf.predict(X_test)

from sklearn.metrics import confusion_matrix
CF_train=confusion_matrix(y_train,SVCPredict_train)
CF_test=confusion_matrix(y_test,SVCPredict_test)
print('Confusion Metrics Train:\n',CF_train)
print('Confusion Metrics Test:\n',CF_test)

Confusion Metrics Train:
 [[3503  132]
 [ 178 1117]]
Confusion Metrics Test:
 [[1283  256]
 [ 265  309]]


In [46]:
print('class weight',clf.class_weight_)

class weight [1. 1.]


In [48]:
print(clf.class_weight)

None


In [50]:
print(clf.classes_)

['No' 'Yes']


In [51]:
clf.coef0

0.0

In [52]:
clf.decision_function_shape

'ovr'

In [53]:
clf.decision_function

<bound method BaseSVC.decision_function of SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)>

In [54]:
clf.dual_coef_

array([[-0.27860499, -1.        , -1.        , ...,  1.        ,
         0.79092971,  1.        ]])