# Amazon Fine Food Reviews Analysis


Data Source: https://www.kaggle.com/snap/amazon-fine-food-reviews <br>

EDA: https://nycdatascience.com/blog/student-works/amazon-fine-foods-visualization/


The Amazon Fine Food Reviews dataset consists of reviews of fine foods from Amazon.<br>

Number of reviews: 568,454<br>
Number of users: 256,059<br>
Number of products: 74,258<br>
Timespan: Oct 1999 - Oct 2012<br>
Number of Attributes/Columns in data: 10 

Attribute Information:

1. Id
2. ProductId - unique identifier for the product
3. UserId - unqiue identifier for the user
4. ProfileName
5. HelpfulnessNumerator - number of users who found the review helpful
6. HelpfulnessDenominator - number of users who indicated whether they found the review helpful or not
7. Score - rating between 1 and 5
8. Time - timestamp for the review
9. Summary - brief summary of the review
10. Text - text of the review


#### Objective:
Given a review, determine whether the review is positive (rating of 4 or 5) or negative (rating of 1 or 2).

<br>
[Q] How to determine if a review is positive or negative?<br>
<br> 
[Ans] We could use Score/Rating. A rating of 4 or 5 can be cosnidered as a positive review. A rating of 1 or 2 can be considered as negative one. A review of rating 3 is considered nuetral and such reviews are ignored from our analysis. This is an approximate and proxy way of determining the polarity (positivity/negativity) of a review.




In [370]:
import gensim
import nltk
import pandas as pd
import numpy as np
import re
import nltk
from nltk import FreqDist
nltk.download('stopwords') # run this one time

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\prudi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [371]:
import pandas as pd
pd.set_option("display.max_colwidth", 200)
import numpy as np
import re
import spacy
import matplotlib.pyplot as plt
import seaborn as sns
import gensim
from gensim import corpora

In [372]:
import os
#os.chdir('C:\\Users\\Administrator\\Desktop\\Data\\reviews_Automotive_5.json')
os.chdir('C:\\Users\\prudi\\Desktop\\Data Sets\\amazon-fine-food-reviews')
#df = pd.read_json('Reviews.json', lines=True)
df=pd.read_csv('Reviews.csv')

In [373]:
df.loc[df['ProductId'] == 'B000HDOPZG',:]

Id   ProductId          UserId  \
73779  73780  B000HDOPZG   ANHNUHKI585T7   
73780  73781  B000HDOPZG   AQFTBJZPVNMAH   
73781  73782  B000HDOPZG  A2G2DXPFZKG48W   
73782  73783  B000HDOPZG   AL1DVFEY7X5VR   
73783  73784  B000HDOPZG  A2F64XFMO5ELL6   
73784  73785  B000HDOPZG  A16SDTBEKKFN2Z   
73785  73786  B000HDOPZG   AI47WBE7PHESF   
73786  73787  B000HDOPZG   ALT34F4DUTJ8Z   
73787  73788  B000HDOPZG  A3BIN78AJ0D4JO   
73788  73789  B000HDOPZG   AKFGO1HY01B85   
73789  73790  B000HDOPZG   AC8BTB2WUNHW9   
73790  73791  B000HDOPZG   AR5J8UI46CURR   
73791  73792  B000HDOPZG  A1SWRA9CZN7GCW   
73792  73793  B000HDOPZG   AWIW6ZQ47MNJH   
73793  73794  B000HDOPZG   AY12DBB0U420B   
73794  73795  B000HDOPZG  A1AU6XU1K1QVHN   
73795  73796  B000HDOPZG  A2D1LPEUCTNT8X   
73796  73797  B000HDOPZG  A2O26F56G0S8GE   
73797  73798  B000HDOPZG   A4O09N7ZP26RD   
73798  73799  B000HDOPZG  A32UUBSGHW403P   
73799  73800  B000HDOPZG   A117ZFKI6BJFD   
73800  73801  B000HDOPZG   AWCHAO9KUQE9T   
73801  73802  B000HDOPZG  A152WV7RWE5QJI   
73802  73803  B000HDOPZG  A2XJKCHDT5NNAA   
73803  73804  B000HDOPZG  A3H8IP3GIN1X10   
73804  73805  B000HDOPZG  A1YB6NIBCOYBB1   
73805  73806  B000HDOPZG  A2BTJ1N6R98NOZ   
73806  73807  B000HDOPZG  A2FL5O5DXWE4QI   
73807  73808  B000HDOPZG   AKX3Q0T86RL5F   
73808  73809  B000HDOPZG  A3262S1NGMJBYL   
73809  73810  B000HDOPZG  A3RZT14XBX7QYQ   
73810  73811  B000HDOPZG  A35XXRYS8FUHRR   
73811  73812  B000HDOPZG  A3C64T6IRAY8YQ   
73812  73813  B000HDOPZG   A4YZH857YFUV0   
73813  73814  B000HDOPZG  A3GO0TGP9IO9NM   
73814  73815  B000HDOPZG   AIGXHM1NZJSNO   
73815  73816  B000HDOPZG  A19C0CI3QQRVPK   
73816  73817  B000HDOPZG   ARM3Q64UL6NG8   

                                 ProfileName  HelpfulnessNumerator  \
73779                              L. Hirsch                    14   
73780                                  Hippo                     7   
73781                            Audio Maven                     6   
73782                        Always Snackin'                     5   
73783                                  Rod B                     3   
73784                               M. White                     2   
73785                             J. Collins                     2   
73786                                Sassy08                     2   
73787                    MrsDiehl "MrsDiehl"                     2   
73788                               L. Botez                     2   
73789                                   Dean                     2   
73790                        Geetha Krishnan                     2   
73791                      emergencydinosaur                     1   
73792                             S F Norman                     1   
73793                          Gary Peterson                     1   
73794                           Susan Jurist                     1   
73795                              Ali Julia                     1   
73796                     Mech Head "Jeremy"                     1   
73797                            James Sweet                     1   
73798                          Terry Fenwick                     1   
73799                                  Linda                     1   
73800                     Judith A. Ericksen                     1   
73801                                   Apri                     1   
73802                        Monica Kim "MK"                     1   
73803                            fabriccolor                     1   
73804                                 stephG                     1   
73805                         Donna K. Ellis                     1   
73806                       Cristina Balaban                     1   
73807                       S. Xu "tea time"                     1   
73808                                    Eva                     1   
73809                        PC "grammabear"                     1   
73810                               Hao Dong         

In [374]:
df.loc[df['ProductId'] == 'B000HDL1RQ',:]

Id   ProductId          UserId  \
78433  78434  B000HDL1RQ   ANHNUHKI585T7   
78434  78435  B000HDL1RQ   AQFTBJZPVNMAH   
78435  78436  B000HDL1RQ  A2G2DXPFZKG48W   
78436  78437  B000HDL1RQ   AL1DVFEY7X5VR   
78437  78438  B000HDL1RQ  A2F64XFMO5ELL6   
78438  78439  B000HDL1RQ  A16SDTBEKKFN2Z   
78439  78440  B000HDL1RQ   AI47WBE7PHESF   
78440  78441  B000HDL1RQ   ALT34F4DUTJ8Z   
78441  78442  B000HDL1RQ  A3BIN78AJ0D4JO   
78442  78443  B000HDL1RQ   AKFGO1HY01B85   
78443  78444  B000HDL1RQ   AC8BTB2WUNHW9   
78444  78445  B000HDL1RQ   AR5J8UI46CURR   
78445  78446  B000HDL1RQ  A1SWRA9CZN7GCW   
78446  78447  B000HDL1RQ   AWIW6ZQ47MNJH   
78447  78448  B000HDL1RQ   AY12DBB0U420B   
78448  78449  B000HDL1RQ  A1AU6XU1K1QVHN   
78449  78450  B000HDL1RQ  A2D1LPEUCTNT8X   
78450  78451  B000HDL1RQ  A2O26F56G0S8GE   
78451  78452  B000HDL1RQ   A4O09N7ZP26RD   
78452  78453  B000HDL1RQ  A32UUBSGHW403P   
78453  78454  B000HDL1RQ   A117ZFKI6BJFD   
78454  78455  B000HDL1RQ   AWCHAO9KUQE9T   
78455  78456  B000HDL1RQ  A152WV7RWE5QJI   
78456  78457  B000HDL1RQ  A2XJKCHDT5NNAA   
78457  78458  B000HDL1RQ  A3H8IP3GIN1X10   
78458  78459  B000HDL1RQ  A1YB6NIBCOYBB1   
78459  78460  B000HDL1RQ  A2BTJ1N6R98NOZ   
78460  78461  B000HDL1RQ  A2FL5O5DXWE4QI   
78461  78462  B000HDL1RQ   AKX3Q0T86RL5F   
78462  78463  B000HDL1RQ  A3262S1NGMJBYL   
78463  78464  B000HDL1RQ  A3RZT14XBX7QYQ   
78464  78465  B000HDL1RQ  A35XXRYS8FUHRR   
78465  78466  B000HDL1RQ  A3C64T6IRAY8YQ   
78466  78467  B000HDL1RQ   A4YZH857YFUV0   
78467  78468  B000HDL1RQ  A3GO0TGP9IO9NM   
78468  78469  B000HDL1RQ   AIGXHM1NZJSNO   
78469  78470  B000HDL1RQ  A19C0CI3QQRVPK   
78470  78471  B000HDL1RQ   ARM3Q64UL6NG8   

                                 ProfileName  HelpfulnessNumerator  \
78433                              L. Hirsch                    14   
78434                                  Hippo                     7   
78435                            Audio Maven                     6   
78436                        Always Snackin'                     5   
78437                                  Rod B                     3   
78438                               M. White                     2   
78439                             J. Collins                     2   
78440                                Sassy08                     2   
78441                    MrsDiehl "MrsDiehl"                     2   
78442                               L. Botez                     2   
78443                                   Dean                     2   
78444                        Geetha Krishnan                     2   
78445                      emergencydinosaur                     1   
78446                             S F Norman                     1   
78447                          Gary Peterson                     1   
78448                           Susan Jurist                     1   
78449                              Ali Julia                     1   
78450                     Mech Head "Jeremy"                     1   
78451                            James Sweet                     1   
78452                          Terry Fenwick                     1   
78453                                  Linda                     1   
78454                     Judith A. Ericksen                     1   
78455                                   Apri                     1   
78456                        Monica Kim "MK"                     1   
78457                            fabriccolor                     1   
78458                                 stephG                     1   
78459                         Donna K. Ellis                     1   
78460                       Cristina Balaban                     1   
78461                       S. Xu "tea time"                     1   
78462                                    Eva                     1   
78463                        PC "grammabear"                     1   
78464                               Hao Dong         

In [375]:
#Sorting data according to ProductId in ascending order
sorted_data=df.sort_values('ProductId', axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')

In [376]:
#Deduplication of entries
final=sorted_data.drop_duplicates(subset={"UserId","ProfileName","Time","Text"}, keep='first', inplace=False)
final.shape

(393933, 10)

In [377]:
sorted_data[sorted_data.duplicated(['UserId','ProfileName',"Time","Text"])].shape

(174521, 10)

In [378]:
final.shape

(393933, 10)

In [379]:
final=final.reset_index()

In [380]:
final=final.loc[:1000,:]

In [381]:
def partition(x):
    if x < 3:
        return 0
    return 1

#changing reviews with score less than 3 to be positive and vice-versa
actualScore = final['Score']
positiveNegative = actualScore.map(partition) 
final['Score'] = positiveNegative
print("Number of data points in our data", final.shape)
final.head(3)

Number of data points in our data (1001, 11)


index      Id   ProductId          UserId            ProfileName  \
0  150528  150529  0006641040   A25ACLV5KPB4W    Matt Hetling "Matt"   
1  150506  150507  0006641040  A1S4A3IQ2MU7V4  sally sue "sally sue"   
2  150505  150506  0006641040  A2IW4PEEKO2R0U                  Tracy   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     0                       1      1  1108425600   
1                     1                       1      1  1191456000   
2                     1                       1      1  1194739200   

                                      Summary  \
0                 Nice cadence, catchy rhymes   
1               chicken soup with rice months   
2  Love the book, miss the hard cover version   

                                                                                                                                                                                                      Text  
0  In June<br />I saw a charming group<br />of roses all begin<br />to droop<br />I pepped them up<br />with chicken soup!<br />Sprinkle once<br />sprinkle twice<br />sprinkle chicken soup<br />with ...  
1                   This is a fun way for children to learn their months of the year!  We will learn all of the poems throughout the school year.  they like the handmotions which I invent for each poem.  
2  I grew up reading these Sendak books, and watching the Really Rosie movie that incorporates them, and love them. My son loves them too. I do however, miss the hard cover version. The paperbacks se...

In [382]:
from nltk.corpus import stopwords
Stopwords=stopwords.words('english')

In [383]:
for i in range(len(final['Text'])):
    words=nltk.word_tokenize(final['Text'][i])
    withoutstopwords=[word for word in words if word not in Stopwords]
    final['Text'][i]=' '.join(withoutstopwords)

C:\Users\prudi\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [384]:
#remove spacial character: https://stackoverflow.com/a/5843547/4084039
## Remove the special characters
final['Text'] = final['Text'].str.replace("[^a-zA-Z0-9]+", " ")

In [385]:
# remove urls from text python: https://stackoverflow.com/a/40823105/4084039
## Remove the URL'S
import re
final['Text']=final['Text'].apply(lambda x: re.sub(r"http\S+", "", x))

In [386]:
from nltk.stem import PorterStemmer
Stemmer=PorterStemmer()
for i in range(len(final['Text'])):
    tokens=nltk.word_tokenize(final['Text'][i])
    stem_tokens=[Stemmer.stem(token) for token in tokens]
    final['Text'][i]=' '.join(stem_tokens)

C:\Users\prudi\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [387]:
# https://stackoverflow.com/questions/16206380/python-beautifulsoup-how-to-remove-all-tags-from-an-element
## Remove xml tags from the reviews
from bs4 import BeautifulSoup
final['Text']=final['Text'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())

In [388]:
# remove short words (length < 3)
final['Text'] = final['Text'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>2]))

In [389]:
# make entire text lowercase
final['Text'] = [r.lower() for r in final['Text']]

In [390]:
final.head(1)

index      Id   ProductId         UserId          ProfileName  \
0  150528  150529  0006641040  A25ACLV5KPB4W  Matt Hetling "Matt"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     0                       1      1  1108425600   

                       Summary  \
0  Nice cadence, catchy rhymes   

                                                                                                                                                                                                      Text  
0  june saw charm group rose begin droop pep chicken soup sprinkl sprinkl twice sprinkl chicken soup rice thi great book teach children month year the repetit phrase funni littl stori accompani pictu...

In [391]:
# printing some random reviews
sent_0 = final['Text'].values[0]
print(sent_0)
print("="*50)

sent_1000 = final['Text'].values[10]
print(sent_1000)
print("="*50)

sent_1500 = final['Text'].values[20]
print(sent_1500)
print("="*50)

sent_4900 = final['Text'].values[30]
print(sent_4900)
print("="*50)

june saw charm group rose begin droop pep chicken soup sprinkl sprinkl twice sprinkl chicken soup rice thi great book teach children month year the repetit phrase funni littl stori accompani pictur make ideal bedtim read thi nearli good sendak book like where wild thing pierr the boy who did care still carri uniqu brand charm
give five star mauric sendak stori one star print edit book children older copi book familiar previou softcov version order granddaught embarrass give gift look puni the book size postcard think overpr learn lesson buy softcov children book next time get use copi
great price read class like littl travel brochur
set asid least hour day read son point consid connoisseur children book one best santa claus put tree sinc read perpetu love first book taught month year second pleasur read well suit old veri children book worth own most borrow librari thi book howev deserv perman spot shelf sendak best


In [392]:
# https://stackoverflow.com/a/47091490/4084039
import re

def decontracted(phrase):
    # specific
    phrase = re.sub(r"won't", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)

    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    return phrase

In [393]:
final['Text']=final['Text'].map(decontracted)

In [394]:
#remove words with numbers python: https://stackoverflow.com/a/18082370/4084039
final['Text']=final['Text'].apply(lambda x: re.sub("\S*\d\S*", "", x))

In [395]:
final.head(2)

index      Id   ProductId          UserId            ProfileName  \
0  150528  150529  0006641040   A25ACLV5KPB4W    Matt Hetling "Matt"   
1  150506  150507  0006641040  A1S4A3IQ2MU7V4  sally sue "sally sue"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     0                       1      1  1108425600   
1                     1                       1      1  1191456000   

                         Summary  \
0    Nice cadence, catchy rhymes   
1  chicken soup with rice months   

                                                                                                                                                                                                      Text  
0  june saw charm group rose begin droop pep chicken soup sprinkl sprinkl twice sprinkl chicken soup rice thi great book teach children month year the repetit phrase funni littl stori accompani pictu...  
1                                                                                                         thi fun way children learn month year learn poem throughout school year like handmot invent poem

In [2]:
#remove words with numbers python: https://stackoverflow.com/a/18082370/4084039
import re
sent_0 = re.sub("\S*\d\S*", "", "This are number 123")
print(sent_0)

This are number 


In [397]:
final.head(1)

index      Id   ProductId         UserId          ProfileName  \
0  150528  150529  0006641040  A25ACLV5KPB4W  Matt Hetling "Matt"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     0                       1      1  1108425600   

                       Summary  \
0  Nice cadence, catchy rhymes   

                                                                                                                                                                                                      Text  
0  june saw charm group rose begin droop pep chicken soup sprinkl sprinkl twice sprinkl chicken soup rice thi great book teach children month year the repetit phrase funni littl stori accompani pictu...

In [398]:
# Combining all the above stundents 
from tqdm import tqdm
preprocessed_reviews = []
# tqdm is for printing the status bar
for sentance in tqdm(final['Text'].values):
    sentance = re.sub(r"http\S+", "", sentance)
    sentance = BeautifulSoup(sentance, 'lxml').get_text()
    sentance = decontracted(sentance)
    sentance = re.sub("\S*\d\S*", "", sentance).strip()
    sentance = re.sub('[^A-Za-z]+', ' ', sentance)
    # https://gist.github.com/sebleier/554280
    sentance = ' '.join(e.lower() for e in sentance.split() if e.lower() not in Stopwords)
    preprocessed_reviews.append(sentance.strip())

100%|████████████████████████████████████████████████████████████████████████████| 1001/1001 [00:00<00:00, 2388.22it/s]


In [399]:
final['Text']=preprocessed_reviews

In [428]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

no_features = 20

# NMF is able to use tf-idf
tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, max_features=no_features, stop_words='english')
tfidf = tfidf_vectorizer.fit_transform(df['Text'])
tfidf_feature_names = tfidf_vectorizer.get_feature_names()

# LDA can only use raw term counts for LDA because it is a probabilistic graphical model
tf_vectorizer = CountVectorizer(max_df=0.95, min_df=2, max_features=no_features, stop_words='english')
tf = tf_vectorizer.fit_transform(df['Text'])
tf_feature_names = tf_vectorizer.get_feature_names()

print('Top columns \n',tf_feature_names)

pd.DataFrame(tf.toarray(),columns=tf_feature_names)

Top columns 
 ['amazon', 'br', 'buy', 'coffee', 'don', 'flavor', 'food', 'good', 'great', 'just', 'like', 'little', 'love', 'product', 'really', 'taste', 'tea', 'time', 'use', 've']


amazon  br  buy  coffee  don  flavor  food  good  great  just  like  \
0            0   0    0       0    0       0     1     1      0     0     1   
1            0   0    0       0    0       0     0     0      0     0     0   
2            0   0    0       0    0       0     0     0      0     0     0   
3            0   0    0       0    0       1     0     1      0     0     0   
4            0   0    0       0    0       0     0     0      2     0     0   
5            0   0    0       0    0       0     0     0      0     1     0   
6            0   0    0       0    0       0     0     0      1     0     0   
7            0   0    0       0    0       0     0     1      0     0     0   
8            0   0    0       0    0       0     0     0      0     1     0   
9            0   0    0       0    0       0     1     2      0     0     0   
10           0   6    0       0    2       0     0     0      0     2     0   
11           0   0    0       0    0       0     4     0      0     0     0   
12           0   0    0       0    0       0     4     0      0     1     0   
13           0   0    0       0    0       1     0     1      0     0     0   
14           0   0    0       0    0       0     0     0      0     0     0   
15           0   0    0       0    0       0     0     0      0     0     0   
16           0   0    0       0    0       0     0     1      0     0     1   
17           0   0    0       0    0       0     0     0      0     0     0   
18           0   2    0       0    0       0     0     0      0     0     1   
19           0   0    0       0    0       0     0     0      0     0     0   
20           1   0    0       0    0       0     0     0      0     0     0   
21           1   1    0       0    0       0     0     0      0     0     0   
22           0   0    0       0    0       0     0     0      0     0     0   
23           0   0    0       0    0       0     0     0      0     0     0   
24           0   1    1       0    0       0     0     0      0     0     0   
25           1   2    0       0    0       0     0     0      0     0     0   
26           0   0    1       0    0       1     0     0      0     2     0   
27           1   1    0       0    0       0     0     0      1     0     0   
28           0   1    0       0    0       0     0     0      1     1     0   
29           0   6    0       0    2       0     0     0      0     2     0   
...        ...  ..  ...     ...  ...     ...   ...   ...    ...   ...   ...   
568424       0   0    0       0    0       1     0     0      0     0     1   
568425       0   2    0       0    0       1     0     1      0     0     0   
568426       0   0    0       0    0       0     0     0      0     0     1   
568427       0   2    0       0    0       0     0     0      0     0     0   
568428       0   1    0       0    0       1     0     0      0     0     0   
568429       0   0    0       0    0       1     0     0      0     0     0   
568430       0   1    0       0    0       0     0     0      0     0     0   
568431       0   0    1       0    0       0     0     0      0     0     1   
568432       0   0    0       0    0       0     0     1      0     0     1   
568433       0   6    1       0    0       0     1     1      0     2     1   
568434       0   0    0       0    0       0     0     0      0     0     1   
568435       0   0    0       0    0       0     0     1      0     0     1   
568436       0   0    1       0    0       0     0     0      0     1     0   
568437       0   0    1       0    0       0     0     0      0     0     0   
568438       0   0    0       0    0       0     0     0      0     0     0   
568439       0   1    0       0    0       0     0     0      0     0     0   
568440       0   0    1       0    0       0     1     0      0     0     0   
568441       0   0    0       0    0       0     0     1      0     0     0   
568442       0   0    0       0    0       0     0     0  

In [429]:
from sklearn.decomposition import NMF, LatentDirichletAllocation

no_topics = 20

# Run NMF
#nmf = NMF(n_components=no_topics, random_state=1, alpha=.1, l1_ratio=.5, init='nndsvd').fit(tfidf)

# Run LDA
lda = LatentDirichletAllocation(n_components=no_topics, max_iter=5, learning_method='online', learning_offset=50.,random_state=0).fit(tf)


In [430]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print ('Topic %d:' % (topic_idx))
        print (" ".join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))

no_top_words = 10
#display_topics(nmf, tfidf_feature_names, no_top_words)
display_topics(lda, tf_feature_names, no_top_words)

Topic 0:
really don like good ve just taste br great flavor
Topic 1:
time don ve like good just br great product love
Topic 2:
great don ve good like love taste just product flavor
Topic 3:
buy don ve like good just br great taste product
Topic 4:
br don ve like just good taste product flavor great
Topic 5:
little don like ve just good br taste great love
Topic 6:
use don ve like good just br product great taste
Topic 7:
good ve don just br taste flavor great product love
Topic 8:
food don ve like br just good love product great
Topic 9:
just don like ve good br taste love great flavor
Topic 10:
flavor don like ve good just taste br great love
Topic 11:
tea don ve like taste flavor good br just love
Topic 12:
like good don taste just br flavor really product great
Topic 13:
coffee don like ve good taste flavor just br love
Topic 14:
product don ve like good br just amazon great taste
Topic 15:
amazon don ve product br good like just great love
Topic 16:
love don ve like just good great

In [431]:
for topic_id,topic in enumerate(lda.components_):
    print(topic_id)
    print(topic.argsort())

0
[16  3  6  2 18  0 17 11 12 13  5  8  1 15  9 19  7 10  4 14]
1
[16  3  6  2 18 11 14  5  0 15 12 13  8  1  9  7 10 19  4 17]
2
[16  6  3  2 11 18 17 14  0  1  5 13  9 15 12 10  7 19  4  8]
3
[16  3  6 18 11 14 17  5 12  0 13 15  8  1  9  7 10 19  4  2]
4
[16  3  2  6 18 11  0 12 14 17  8  5 13 15  7  9 10 19  4  1]
5
[16  3  0  6  2 18 17 14 13  5 12  8 15  1  7  9 19 10  4 11]
6
[16  6  3  2  0 14 11 17  5 12 15  8 13  1  9  7 10 19  4 18]
7
[16  6  3  2 18 10 11 17  0 14 12 13  8  5 15  1  9  4 19  7]
8
[ 3 16  5 18 15  2  0 11 14 17  8 13 12  7  9  1 10 19  4  6]
9
[16  3  6  2  0 18 17 11 14 13  5  8 12 15  1  7 19 10  4  9]
10
[ 6 16  2  0 18 17  3 11 13 14 12  8  1 15  9  7 19 10  4  5]
11
[ 6  3  2 11 13 18  0 17 14  8 12  9  1  7  5 15 10 19  4 16]
12
[19 16  3  6  2  0 18 17 12 11  8 13 14  5  1  9 15  4  7 10]
13
[ 6 16 11  2 17 14 13 18  0  8 12  1  9  5 15  7 19 10  4  3]
14
[16  3  6 11  2 14 17  5 18 12 15  8  0  9  1  7 10 19  4 13]
15
[16  3 11 18  6 14  5 17  2 15 1